#!/usr/bin/python3

import ast
import json
import sys

stdin: str = "".join(sys.stdin.readlines())

try:
    parsed = ast.literal_eval(stdin)
    stdout = json.dumps(parsed, indent=4, default=str)
except (ValueError, SyntaxError):
    stdout = stdin

print(stdout)
